### PR TITLE
fix: Fix pathType warnings on ingress resources

### LINKED ISSUE #21: helm deployment: Warnings on ingress configuration
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
All

### Is this a regression?
Yes, this warning is new, may be newly introduced error checking.

## 🔥 Exception or Error
<pre><code>
$ helm install edgex-minnesota -n edgex .
W0920 14:47:39.425171  251459 warnings.go:70] path /rules-engine/(.*) cannot be used with pathType Prefix
W0920 14:47:39.425355  251459 warnings.go:70] path /core-consul/(.*) cannot be used with pathType Prefix
W0920 14:47:39.438260  251459 warnings.go:70] path /vault/(v1/auth/userpass/login/.*) cannot be used with pathType Prefix
W0920 14:47:39.438276  251459 warnings.go:70] path /vault/(v1/identity/oidc/token/.*) cannot be used with pathType Prefix
W0920 14:47:39.438260  251459 warnings.go:70] path /core-command/(.*) cannot be used with pathType Prefix
W0920 14:47:39.438737  251459 warnings.go:70] path /core-metadata/(.*) cannot be used with pathType Prefix
W0920 14:47:39.438773  251459 warnings.go:70] path /support-notifications/(.*) cannot be used with pathType Prefix
W0920 14:47:39.438733  251459 warnings.go:70] path /support-scheduler/(.*) cannot be used with pathType Prefix
W0920 14:47:39.453850  251459 warnings.go:70] path /device-virtual/(.*) cannot be used with pathType Prefix
W0920 14:47:39.453996  251459 warnings.go:70] path /core-data/(.*) cannot be used with pathType Prefix
</code></pre>

## 🌍  Your Environment
**Deployment Environment:** k8s on fedora

**EdgeX Version [**REQUIRED**]:** main (pending 3.1)

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by bnevis-i**
Closes #21

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
Install helm chart as usual

### CODE REVIEW

**Review by jim-wang-intel — COMMENTED** [review]
don't remember what version of Kubernetes we required, only version 1.18 or above has this pathType feature

**Comment by jim-wang-intel** [comment]
> don't remember what version of Kubernetes we required, only version 1.18 or above has this pathType feature

https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/ 
in section **New Features Available in Kubernetes 1.18 and Above**

**Comment by bnevis-i** [comment]
> > don't remember what version of Kubernetes we required, only version 1.18 or above has this pathType feature
> 
> https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/ in section **New Features Available in Kubernetes 1.18 and Above**

https://kubernetes.io/releases/

_The Kubernetes project maintains release branches for the most recent three minor releases (1.28, 1.27, 1.26). Kubernetes 1.19 and newer receive [approximately 1 year of patch support](https://kubernetes.io/releases/patch-releases/#support-period). Kubernetes 1.18 and older received approximately 9 months of patch support._

1.17 reached end of support on 25 Dec 2020. (https://endoflife.date/kubernetes)

**Comment by jim-wang-intel** [comment]
> > > don't remember what version of Kubernetes we required, only version 1.18 or above has this pathType feature
> > 
> > 
> > https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/ in section **New Features Available in Kubernetes 1.18 and Above**
> 
> https://kubernetes.io/releases/
> 
> _The Kubernetes project maintains release branches for the most recent three minor releases (1.28, 1.27, 1.26). Kubernetes 1.19 and newer receive [approximately 1 year of patch support](https://kubernetes.io/releases/patch-releases/#support-period). Kubernetes 1.18 and older received approximately 9 months of patch support._
> 
> 1.17 reached end of support on 25 Dec 2020. (https://endoflife.date/kubernetes)

ok, it is interesting in that ngnix docs, it says `The ImplementationSpecific pathType is treated as equivilent to Prefix pathType, with the exception that when this pathType is configured, the path field in spec.rules[].http.paths[] is not mandatory. path defaults to / if not set but the pathType is set to ImplementationSpecific.`

**Review by jim-wang-intel — APPROVED** [review]

**Comment by bnevis-i** [comment]
> ok, it is interesting in that ngnix docs, it says `The ImplementationSpecific pathType is treated as equivilent to Prefix pathType, with the exception that when this pathType is configured, the path field in spec.rules[].http.paths[] is not mandatory. path defaults to / if not set but the pathType is set to ImplementationSpecific.`

I can't make sense of that, but the regexp is needed for the rewrite rule and when I use ImplementationSpecific the warning goes away :-)

**Pull request merged**
